### PR TITLE
Array algebra index set merge

### PR DESCRIPTION
**Pull request by rohany**
Pull in index set changes

### CODE REVIEW

**Comment by rohany** [comment]
@RawnH can you look at this test failure `scheduling_eval.bfsPullScheduled`?

**Comment by RawnH** [comment]
@rohany Sure, I will take a look at fixing this

**Comment by rohany** [comment]
@RawnH  did you get a chance to look at this yet?

**Comment by RawnH** [comment]
@rohany Unfortunately not. I should have some time this week. If not, I will take a look over the weekend.

**Comment by rohany** [comment]
I'm going to temporarily disable the failing tests for us to look into later. @stephenchouca can you merge this?

**Pull request merged**
