### PR TITLE
CLI tests

### PR DESCRIPTION
**Pull request by Infinoid**
This adds test cases for the taco CLI tool.  It pulls in [bats](https://github.com/bats-core/bats-core), a bash unit testing suite, as a submodule.

Currently it provides some test coverage for:

* usage information printed when called without any arguments
* `-help`
* `-help=scheduling`
* `-version`
* basic code generation
  * it makes sure the code actually compiles
  * it compiles with `-pedantic` to catch undefined variables
* -f=format
  * matrix multiply with permutations of dd, ds, sd, ss inputs
* -t=type
  * every input type on RHS, matching type on LHS
  * every input type on RHS, double type on LHS
* -s=schedule
  * reorder
  * split
  * divide
  * fuse
  * pos
  * precompute
  * bound
  * unroll
  * assemble
  * parallelize

This brings the test coverage of `tools/taco.cpp` from 0% to 63.7%.

It's not perfect, but I think this is a good starting point.  Further improvements can be added in later PRs.

### CODE REVIEW

**Comment by rohany** [comment]
I would definitely add bats as a submodule, rather than including the whole source here.

For sake of argument, what is the benefit of using `bats` over something simpler like `expect` (example here https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/interactive_tests/test_demo.tcl) -- it mimics a "execute command in the shell and make sure that the response looks like something"

**Comment by Infinoid** [comment]
> I would definitely add bats as a submodule, rather than including the whole source here.

If that's the case, would you do the same thing for `test/gtest` and `python_bindings/pybind11`?  I don't have a strong opinion about this either way.  But one problem I see is that git doesn't clone submodules by default.

Another approach would be to only bundle the parts that are necessary for executing tests.  The bats-core release tarball contains docs and unit tests for bats itself, which are not necessary for taco.

**Comment by Infinoid** [comment]
> For sake of argument, what is the benefit of using `bats` over something simpler like `expect`

Laziness, I guess.

It's a test framework, with all of the normal features you'd expect.  It gives us a clear syntax for defining tests, names, implementations and success criteria, it has setup/teardown hooks, it lets you skip tests, and it collapses the output down to a single line when the tests are passing.  We use the googletest framework for C++ tests, for probably the same reasons.

I'm not opposed to using other tools, but I do want to minimize effort and maximize utility.  I don't think using `expect` would be an improvement here.

**Comment by rohany** [comment]
> If that's the case, would you do the same thing for test/gtest and python_bindings/pybind11? I don't have a strong opinion about this either way. But one problem I see is that git doesn't clone submodules by default.

I would have done so. Cloning of submodules can occur as a pre build step in the build configuration.

> It's a test framework, with all of the normal features you'd expect. It gives us a clear syntax for defining tests, names, implementations and success criteria, it has setup/teardown hooks, it lets you skip tests, and it collapses the output down to a single line when the tests are passing. We use the googletest framework for C++ tests, for probably the same reasons.

Makes sense -- I've never used `bats` before. Just wanted to make sure some options were considered.

**Comment by Infinoid** [comment]
Updated to use a submodule for bats.

`tools/taco.cpp` test coverage now at 47.6% (from 0%)

**Pull request merged**
