### PR TITLE
Generalizes TACO Merge lattice construction

### PR DESCRIPTION
**Pull request by rawnhenry**
This PR should now be largely functional on for the TACO CPU build.

This PR attempts to generalize the lattice construction of TACO. It largely implements the concepts discussed in this [Master thesis](https://dspace.mit.edu/handle/1721.1/127406). In short, this PR adds:

1. A generalized theory for Merge lattice construction - TACO can construct lattices for any iteration space instead of just complements and unions.
2. Introduces the concept of a fill value in TACO.
3. Introduces operator properties and allows TACO to infer some basic optimizations from these properties.

Why this is still in draft (TODO in priority order. ETA mid Feb)
1. ~~Fix bug from merge :(~~
2. ~~Fix segfault due to fill value with GPU backend :(~~
3. ~~Fix compiler crash when using indexVars that have been scheduled as the operands to funcs~~
4. ~~Fix segfault when running GPU spmv schedule~~ - Looks like this is the same issue as #389, will not fix
5. The Merge Lattice implementation does not match the theory discussed in the thesis. The new theory is much simpler, requiring none of the complicated bookkeeping currently done in the code. 
6. The code responsible for extracting iteration algebra from Index Expressions currently does not handle nested Funcs.
7. The code responsible for short circuiting will fail if attempting to break out of multiple loops. Need to add mechanism to detect this and insert goto statements when necessary. This is just a performance bug.

Current Limitations:
1. Currently, TACO default to fill value of zero whenever one is not specified (this is done in the constructor of the tensorVar). It would be nice to do this for only RHS operands and allow TACO to set the fill value of LHS expressions during computation.

### CODE REVIEW

**Comment by RawnH** [comment]
The slice multiple ways test fails after the most recent merge from master. If you have a chance, would you mind taking a look @rohany?

It also seems that WindowedIndexVars should also inherit from IndexExpr so that they can be used in computations.

**Comment by rohany** [comment]
> The slice multiple ways test fails after the most recent merge from master. If you have a chance, would you mind taking a look @rohany?

I looked into it and opened a PR here https://github.com/RawnH/taco/pull/1. I believe that merging on your repository will cause this PR to get updated. I double checked that `make test` passes on that commit. This wasn't a fun one to track down though.

> It also seems that WindowedIndexVars should also inherit from IndexExpr so that they can be used in computations.

The way I have this set up is that anything windowing related folds into an `Access` and is handled in lowering when looking at `Access` objects, rather than dealing with `WindowedIndexVar`'s everywhere.

**Comment by rohany** [comment]
Once that PR is merged, we can set up the new branch. However, I don't have write permission here, so I wouldn't be able to make it. @stephenchouca either you can make the branch or add me and I'll make it.

**Comment by stephenchouca** [comment]
I've created a new `array_algebra` branch based off of the current master. You should be able to modify this PR to merge into that branch.

**Pull request merged**
