### PR TITLE
Teach CMake how to run the tests via "make test"

### PR DESCRIPTION
**Pull request by Infinoid**
This makes `make test` run the tests.

The C++ (gtest) tests are run in all builds.  The cmake version requirement is bumped to 3.0, to get integration with the gtest framework that the C++ tests use.  Cmake 3.0 came out in 2014, so most folks have it by now.  (https://repology.org/project/cmake/versions)

When the Python build is enabled (`-DPYTHON=ON`), the python tests are also run.  A copy of `unit_tests.py` is staged in the build folder, with the staging path added to the beginning of `sys.path`.  This lets it run against the staged `.py` and `.so` files.

The `make test` output has a summary at the end, which looks like this:

```
[snip]
        Start 157: type.Shape
157/159 Test #157: type.Shape .....................................   Passed    0.18 sec
        Start 158: type.TensorType
158/159 Test #158: type.TensorType ................................   Passed    0.18 sec
        Start 159: pytaco
159/159 Test #159: pytaco .........................................   Passed    7.11 sec

100% tests passed, 0 tests failed out of 149

Total Test time (real) =  81.32 sec

The following tests did not run:
	 16 - expr.accumulate (Disabled)
	 68 - qcd.mul3 (Disabled)
	 84 - generate_evaluation_files.cpu (Disabled)
	 85 - generate_evaluation_files.gpu (Disabled)
	 86 - generate_figures.cpu (Disabled)
	138 - tensor_types.complex_mul_scalar (Disabled)
	143 - tensor_types.coordinate_types (Disabled)
	149 - lower.transpose (Disabled)
	150 - lower.transpose2 (Disabled)
	151 - lower.transpose3 (Disabled)
```

If you set `CTEST_PARALLEL_LEVEL=8` in the environment, it will run 8 tests at once, which speeds things up quite a bit for me.

### CODE REVIEW

**Comment by stephenchouca** [comment]
When I run cmake with this change, I get the message "Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)" though I was still able to build and run taco successfully. Do you have any insight into this?

**Comment by Infinoid** [comment]
Yeah.  I get the same message, but it is still able to find and run the tests successfully.

I think it's trying to find a system-installed gtest.  But taco bundles its own copy of gtest, which is all that's needed.  I will see if I can clean that up a little.

**Comment by Infinoid** [comment]
The message is harmless.

The `FindGTest` module in cmake does two things:

1. tries to detect a system-installed gtest, so that the project can build test cases against it
2. provides the ability for cmake to inspect a built gtest executable and run the tests via ctest

The patch makes use of feature #2, but #1 comes along for the ride, and causes a useless failure message when you run cmake.

One solution is to just ignore the message.

Another solution is to bump the cmake requirement to 3.9 and use `GoogleTest` instead.  In cmake 3.9, the two features were split up, so that #1 is done by `FindGTest` and #2 is done by `GoogleTest`.  This works well on my machine, with no failure messages when you run cmake.  But it will make it harder to build on older machines.  It will work on Debian 10 (stable) and Ubuntu 18.04, but not Debian 9 (oldstable) or Ubuntu 16.04.

Another solution: don't use CMake's gtest integration at all, teach cmake to just run the `taco-test` binary directly.  This is widely compatible with old versions of cmake, but it loses the ability to run tests in parallel.

**Comment by stephenchouca** [comment]
Would it be possible then to test for the version of cmake being used and include `GoogleTest` instead if 3.9 or above is present? That way we'd at least prevent the message from being shown where possible.

**Comment by Infinoid** [comment]
That's a good idea, I updated the patch do that.

If using cmake 3.9.0+, it uses the GoogleTest module to run and report individual test cases separately, and optionally run them in parallel.  If not, it runs `taco-test` binary as a single test case without inspecting it at all.  I tested this with a bunch of cmake versions, and it works everywhere, with no GTest errors.

cmake 3.8.2 says:
```
Running tests...
Test project /home/infinoid/workspace/taco/cmake-tests/3.8.2-build-bare-Release
    Start 1: taco-test
1/1 Test #1: taco-test ........................   Passed  581.29 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 581.32 sec
```

cmake 3.9.6 says:
```Running tests...
Test project /home/infinoid/workspace/taco/cmake-tests/3.9.6-build-bare-Release
        Start   1: */apiset.api/*
  1/158 Test   #1: */apiset.api/* .................................   Passed    2.70 sec
        Start   2: */apiget.api/*
  2/158 Test   #2: */apiget.api/* .................................   Passed    2.98 sec
[...snip...]
        Start 157: type.Shape
157/158 Test #157: type.Shape .....................................   Passed    0.37 sec
        Start 158: type.TensorType
158/158 Test #158: type.TensorType ................................   Passed    0.33 sec

100% tests passed, 0 tests failed out of 148

Total Test time (real) = 711.71 sec

The following tests did not run:
         16 - expr.accumulate (Disabled)
         68 - qcd.mul3 (Disabled)
         84 - generate_evaluation_files.cpu (Disabled)
         85 - generate_evaluation_files.gpu (Disabled)
         86 - generate_figures.cpu (Disabled)
        138 - tensor_types.complex_mul_scalar (Disabled)
        143 - tensor_types.coordinate_types (Disabled)
        149 - lower.transpose (Disabled)
        150 - lower.transpose2 (Disabled)
        151 - lower.transpose3 (Disabled)
```

**Comment by stephenchouca** [comment]
Looks good, thanks!

**Pull request merged**
